apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: psp-readonlyrootfilesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "Policy check failed `K8sPSPReadOnlyRootFilesystem`. Pod should have securityContext.readOnlyRootFilesystem: true"

