apiVersion: v1
kind: Namespace
metadata:
  name: exempted-namespace
  labels:
    # env: development
    owner: niran
    admission.gatekeeper.sh/ignore: "true"
  annotations:
    configsync.gke.io/cluster-name-selector: acm-demo